export enum Subjects {
  NEW_COMPANY_REGISTERED = "NEW_COMPANY_REGISTERED",
  COMPANY_INFO_UPDATED = "COMPANY_INFO_UPDATED",
  NEW_SUBSCRIPTION_CREATED = "NEW_SUBSCRIPTION_CREATED",
  JOB_OFFER_CREATED = "JOB_OFFER_CREATED",
}
